redis:
  image: redis:7
  ports:
    - '6379:6379'

db:
  image: postgres:15
  environment:
    POSTGRES_DB: chatdb
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: pass
  ports:
    - '5432:5432'

web:
  build: ./realtimechat
  command: sh -c "python manage.py migrate && daphne -b 0.0.0.0 -p 8000 realtimechat.asgi:application"
  volumes:
    - ./realtimechat:/app
  ports:
    - '8000:8000'
  links:
    - redis
    - db
      